### PR TITLE
feat: expose route method

### PR DESCRIPTION
**Pull request by jaulz**
This PR restructures `Ziggy` class so it can expose a `route` method (name is up to discussion) that returns a route in the same format as it is exposed in the generated file. In my use case I use it to expose the current route separately:
```php
        $ziggy = new \Tightenco\Ziggy\Ziggy();

        $ziggy
          ->route($request->route())
          ->toArray();
```

### CODE REVIEW

**Comment by jaulz** [comment]
To reduce the app bundle size I use a Babel macro that replaces `route` calls with the actual route definitions (e.g. `route("home")` will be compiled into `{ "uri": "...", "methods": [...], "bindings": [] }` based on the generated JSON file by Ziggy). The only route that I would like to expose is the current route so I can easily manipulate the current URL via Ziggy. Consequently I need it in the format that is expected by the JavaScript class and thus I would simply use a method of this library instead of using my own custom function (that I might need to adapt if the library changes). 

It is a special scenario but I think the changes of this PR would not add any complexity.

**Comment by jaulz** [comment]
@bakerkretzmar any chance to have another look? 😊  thanks in advance!

**Comment by bakerkretzmar** [comment]
@jaulz will revisit this again this week 👍🏻 this would accomplish more or less the same thing, right?

```php
use Tightenco\Ziggy\Ziggy;

(new Ziggy)->toArray()['routes'][$request->route()];
```

**Comment by jaulz** [comment]
@bakerkretzmar sorry to disturb but would you have any chance to have another look at this? 😊

**Comment by jaulz** [comment]
@bakerkretzmar sorry but I will close the PR for the time being but thanks anyway for the great project! In the meantime I moved on and released a framework which is quite similar to Inertia but comes with a lot of new features including injected route definitions via Vite. In terms of route matching it's largely similar to your's, so thanks for that! You can find more details here: https://github.com/navigarejs/framework

**Pull request closed without merging**
