### PR TITLE
Add support for using only and except in group

### PR DESCRIPTION
**Pull request by YeeJiaWei**
### Discussed in https://github.com/tighten/ziggy/discussions/520

### CODE REVIEW

**Comment by hulkur** [comment]
yes, please :) 

just came to look if it is already supported or needs a PR

**Comment by YeeJiaWei** [comment]
yes, I opened an PR

**Comment by bakerkretzmar** [comment]
Thanks! Couple things I noticed that I'll see if I can fix quickly:

- I believe these nested `only` and `except` configs will be ignored if a user passes an array of groups anywhere
- technically it's possible to pass `only` and some route names, and those route names would then be ignored. we should probably validate the structure of the group config just a _bit_ to avoid this

**Comment by bakerkretzmar** [comment]
Actually, decided to solve those issues by taking a slightly different approach, see #559.

**Pull request closed without merging**
