### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by zidingz**
A simple instruction for security researchers.

### CODE REVIEW

**Comment by bradyrenting** [comment]
Just wondering: There already is a security section to be found in the [`README.md`](https://github.com/tighten/ziggy/blob/main/README.md#security). Why is the content in `SECURITY.md` different? 🙂

**Comment by jakebathman** [comment]
There are a few reason for a separate file. If someone had a security-related issue to report, they may not scroll to the bottom of the readme to look for that (and might reach for a `SECURITY.md` by default). GitHub also used the presence of that file in [certain ways](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository), such as showing a link to the file when someone creates a new issue.

**Comment by bradyrenting** [comment]
> There are a few reason for a separate file. If someone had a security-related issue to report, they may not scroll to the bottom of the readme to look for that (and might reach for a `SECURITY.md` by default). GitHub also used the presence of that file in [certain ways](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository), such as showing a link to the file when someone creates a new issue.

Sorry, but I was talking about the content. It's a completely different e-mail address.

**Comment by bakerkretzmar** [comment]
Closed by tighten/.github#1 and I'll update the readme to link there instead.

**Pull request closed without merging**
